export enum ErrorCode {
  // Generic
  INTERNAL_ERROR = 'INTERNAL_ERROR',
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  UNAUTHORIZED = 'UNAUTHORIZED',
  FORBIDDEN = 'FORBIDDEN',
  NOT_FOUND = 'NOT_FOUND',

  // Orders
  ORDER_NOT_FOUND = 'ORDER_NOT_FOUND',
  ORDER_INVALID_STATUS_TRANSITION = 'ORDER_INVALID_STATUS_TRANSITION',
  ORDER_PAYMENT_NOT_SETTLED = 'ORDER_PAYMENT_NOT_SETTLED',
  ORDER_SHIPMENT_NOT_READY = 'ORDER_SHIPMENT_NOT_READY',
  ORDER_STATE_CHANGED = 'ORDER_STATE_CHANGED',
  ORDER_CANNOT_CANCEL = 'ORDER_CANNOT_CANCEL',

  // Payments
  PAYMENT_NOT_FOUND = 'PAYMENT_NOT_FOUND',
  PAYMENT_ALREADY_CONFIRMED = 'PAYMENT_ALREADY_CONFIRMED',
  PAYMENT_FAILED = 'PAYMENT_FAILED',
  PAYMENT_CALLBACK_INVALID = 'PAYMENT_CALLBACK_INVALID',

  // Inventory
  INVENTORY_NOT_AVAILABLE = 'INVENTORY_NOT_AVAILABLE',
  INVENTORY_RESERVATION_FAILED = 'INVENTORY_RESERVATION_FAILED',
  INVENTORY_STATE_CHANGED = 'INVENTORY_STATE_CHANGED',

  // Shipping
  SHIPMENT_NOT_READY = 'SHIPMENT_NOT_READY',
  SHIPMENT_INVALID_STATUS = 'SHIPMENT_INVALID_STATUS',
}
